<a href="https://colab.research.google.com/github/meghansn/glp1-analysis/blob/main/data_viewing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Install essential cloud and data tools
!pip install gcsfs pandas

Requirement already satisfied: gcsfs in /usr/local/lib/python3.12/dist-packages (2025.3.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from gcsfs) (3.13.5)
Requirement already satisfied: decorator>4.1.2 in /usr/local/lib/python3.12/dist-packages (from gcsfs) (4.4.2)
Requirement already satisfied: fsspec==2025.3.0 in /usr/local/lib/python3.12/dist-packages (from gcsfs) (2025.3.0)
Requirement already satisfied: google-auth>=1.2 in /usr/local/lib/python3.12/dist-packages (from gcsfs) (2.47.0)
Requirement already satisfied: google-auth-oauthlib in /usr/local/lib/python3.12/dist-packages (from gcsfs) (1.4.0)
Requirement already satisfied: google-cloud-storage in /usr/local/lib/python3.12/dist-packages (from gcsfs) (3.10.1)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from gcsfs) (2.32.4)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs) (1.24.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth>=1.2->gcsfs) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth>=1.2->gcsfs) (4.9.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from google-auth-oauthlib->gcsfs) (2.0.0)
Requirement already satisfied: google-api-core<3.0.0,>=2.27.0 in /usr/local/lib/python3.12/dist-packages (from google-cloud-storage->gcsfs) (2.30.3)
Requirement already satisfied: google-cloud-core<3.0.0,>=2.4.2 in /usr/local/lib/python3.12/dist-packages (from google-cloud-storage->gcsfs) (2.6.0)
Requirement already satisfied: google-resumable-media<3.0.0,>=2.7.2 in /usr/local/lib/python3.12/dist-packages (from google-cloud-storage->gcsfs) (2.9.0)
Requirement already satisfied: google-crc32c<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from google-cloud-storage->gcsfs) (1.8.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->gcsfs) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->gcsfs) (3.15)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->gcsfs) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->gcsfs) (2026.5.20)
Requirement already satisfied: typing-extensions>=4.2 in /usr/local/lib/python3.12/dist-packages (from aiosignal>=1.4.0->aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs) (4.15.0)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.63.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=2.27.0->google-cloud-storage->gcsfs) (1.75.0)
Requirement already satisfied: protobuf<8.0.0,>=4.25.8 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=2.27.0->google-cloud-storage->gcsfs) (5.29.6)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=2.27.0->google-cloud-storage->gcsfs) (1.28.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth>=1.2->gcsfs) (0.6.3)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib->gcsfs) (3.3.1)

In [2]:
import pandas as pd
import gcsfs

In [3]:
# This will prompt you to authenticate your Google account
# if you haven't already in this specific session
from google.colab import auth
auth.authenticate_user()

In [4]:
# Initialize your connection to GCS
fs = gcsfs.GCSFileSystem(project='my-pharma-data-project')

# List everything in your bucket to verify paths
print("Bucket contents:")
print(fs.ls('my-pharma-data-project'))

Bucket contents:
['my-pharma-data-project/adverse_events.csv', 'my-pharma-data-project/adverse_events_summary.csv', 'my-pharma-data-project/canada-adverse-data', 'my-pharma-data-project/clinical_trials.csv', 'my-pharma-data-project/data_dictionary.csv', 'my-pharma-data-project/drugs_overview.csv', 'my-pharma-data-project/search_trends.csv', 'my-pharma-data-project/stock_prices.csv', 'my-pharma-data-project/wikipedia_summaries.csv']

In [10]:
import pandas as pd

def load_cloud_data(bucket_path):
    # Ensure the path starts with gs://
    if not bucket_path.startswith('gs://'):
        full_path = f'gs://{bucket_path}'
    else:
        full_path = bucket_path

    # Read with tab separation (common for these TXT files)
    # We add encoding='latin1' just in case there are special characters
    return pd.read_csv(full_path, sep='\t', encoding='latin1')

In [11]:
# Now call it with the bucket name included
df = load_cloud_data('my-pharma-data-project/canada-adverse-data/reactions.txt')

# See if it worked
print(df.head())

FileNotFoundError: b/my-pharma-data-project/o/canada-adverse-data%2Freactions.txt

In [13]:
# List exactly what is inside your folder
!gsutil ls gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/

Google recommends using Gcloud storage CLI (https://docs.cloud.google.com/storage/docs/discover-object-storage-gcloud) instead of gsutil. Please refer to migration guide (https://docs.cloud.google.com/storage/docs/gsutil-transition-to-gcloud) for assistance.
gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/drug_product_ingredients.txt
gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/drug_products.txt
gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/gender_lx.txt
gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/literature_reference.txt
gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/outcome_lx.txt
gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/reactions.txt
gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/report_drug.txt
gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/report_drug_indication.txt
gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/report_links.txt
gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/report_type_lx.txt
gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/reports.txt
gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/seriousness_lx.txt
gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/source_lx.txt

In [14]:
# List all files recursively in your data project bucket
!gsutil ls -R gs://my-pharma-data-project/canada-adverse-data/**

Google recommends using Gcloud storage CLI (https://docs.cloud.google.com/storage/docs/discover-object-storage-gcloud) instead of gsutil. Please refer to migration guide (https://docs.cloud.google.com/storage/docs/gsutil-transition-to-gcloud) for assistance.
gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/drug_product_ingredients.txt
gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/drug_products.txt
gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/gender_lx.txt
gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/literature_reference.txt
gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/outcome_lx.txt
gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/reactions.txt
gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/report_drug.txt
gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/report_drug_indication.txt
gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/report_links.txt
gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/report_type_lx.txt
gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/reports.txt
gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/seriousness_lx.txt
gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/source_lx.txt

In [15]:
import pandas as pd

# Define the base path for your extracted data
base_path = 'gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/'

# List of all files to preview
files_to_preview = [
    'drug_product_ingredients.txt', 'drug_products.txt', 'gender_lx.txt',
    'literature_reference.txt', 'outcome_lx.txt', 'reactions.txt',
    'report_drug.txt', 'report_drug_indication.txt', 'report_links.txt',
    'report_type_lx.txt', 'reports.txt', 'seriousness_lx.txt', 'source_lx.txt'
]

print("--- Using Gcloud Storage CLI for verification ---")
# Using the updated command as recommended by Google
!gcloud storage ls {base_path}

# Loop through and display the first 3 rows of each
for filename in files_to_preview:
    full_path = f"{base_path}{filename}"
    print(f"\n--- Preview of: {filename} ---")
    try:
        # Most of these government files are tab-delimited
        df = pd.read_csv(full_path, sep='\t', encoding='latin1')
        display(df.head(3))
    except Exception as e:
        print(f"Could not load {filename}: {e}")

--- Using Gcloud Storage CLI for verification ---
gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/drug_product_ingredients.txt
gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/drug_products.txt
gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/gender_lx.txt
gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/literature_reference.txt
gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/outcome_lx.txt
gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/reactions.txt
gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/report_drug.txt
gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/report_drug_indication.txt
gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/report_links.txt
gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/report_type_lx.txt
gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/reports.txt
gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/seriousness_lx.txt
gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/source_lx.txt

--- Preview of: drug_product_ingredients.txt ---

  113507991$"1135"$"PROCHLORPERAZINE MESYLATE INJ 5MG/ML"$"7991"$"prochlorperazine"
0  3806807996$"38068"$"STELAZINE"$"7996"$"trifluo...
1  3806907996$"38069"$"STELABID"$"7996"$"trifluop...
2  4346007996$"43460"$"TRIFLURIN"$"7996"$"trifluo...

--- Preview of: drug_products.txt ---

                                   1$"DELATESTRYL"
0                     2$"DELATESTRYL INJ 200MG/ML"
1  3$"TEMPRA CEMENT POWDER AND TEMPRA POLY LIQUID"
2                                     4$"MAGNOLAX"

--- Preview of: gender_lx.txt ---

     41$"1"$"Male"$"Masculin"
0  42$"2"$"Female"$"FÃ©minin"

--- Preview of: literature_reference.txt ---
Could not load literature_reference.txt: Error tokenizing data. C error: Expected 1 fields in line 255717, saw 2


--- Preview of: outcome_lx.txt ---

                      1906$"06"$"Unknown"$"Inconnue"
0         1907$"07"$"Recovered/resolved"$"GuÃ©rison"
1  1908$"08"$"Recovering/resolving"$"GuÃ©rison en...
2  1909$"09"$"Not recovered/not resolved"$"Non rÃ...

--- Preview of: reactions.txt ---

  5601$"56"$""$""$""$"Rash"$"Rash"$"Skin and subcutaneous tissue disorders"$"Affections de la peau et du tissu sous-cutanÃ©"$"v.27.1"
0  5701$"57"$""$""$""$"Irritability"$"Irritabilit...
1  5801$"58"$""$""$""$"Conjunctivitis"$"Conjoncti...
2  5803$"58"$""$""$""$"Photophobia"$"Photophobie"...

--- Preview of: report_drug.txt ---

  177$"183405"$"44130"$"PRIMROSE OIL"$"Concomitant"$"Concomitant"$"Unknown"$"Inconnu"$""$""$""$""$""$""$""$""$""$""$""$""$"NOT SPECIFIED"$"NON PRÃCISÃE"
0  178$"183405"$"21895"$"IRON"$"Concomitant"$"Con...
1  179$"183405"$"39717"$"NIZATIDINE"$"Concomitant...
2  180$"183405"$"36464"$"PROPRANOLOL"$"Concomitan...

--- Preview of: report_drug_indication.txt ---

  3891781$"300248"$"8248"$"REMICADE"$"Crohn's disease"$"Maladie de Crohn"
0  4016384$"300172"$"6353"$"APO-PAROXETINE"$"Depr...
1  3977480$"300451"$"4743"$"BETASERON"$"Secondary...
2  3891805$"300273"$"9473"$"CHAMPIX"$"Smoking ces...

--- Preview of: report_links.txt ---

  1432411$"143241"$"Duplicate"$"Doublon"$"000307652"
0  1433901$"143390"$"Duplicate"$"Doublon"$"000143...
1  1436082$"143608"$"Duplicate"$"Doublon"$"000323...
2  1436211$"143621"$"Duplicate"$"Doublon"$"000338...

--- Preview of: report_type_lx.txt ---

                 70095001$"5001"$"CMDSNet"$"ResSCMM"
0  70095002$"5002"$"Investigational Testing"$"Ess...
1                70095007$"5"$"Published"$"PubliÃ©e"
2  70095009$"7"$"Spontaneous"$"DÃ©claration spont...

--- Preview of: reports.txt ---

  1$"000000001"$"0"$"05-JUN-73"$"05-JUN-73"$""$"7"$"Spontaneous"$"DÃ©claration spontanÃ©e"$"2"$"Female"$"FÃ©minin"$"62"$"62"$"Years"$"AnnÃ©es"$"06"$"Unknown"$"Inconnue"$"66"$"Kilogram"$"Kilogramme"$"155"$"Centimeter"$"CentimÃ¨tres"$"02"$"Not Serious"$"Non grave"$""$""$""$""$""$""$"Physician"$"Physicien"$""$""$""$""$""$""
0  2$"000000002"$"0"$"05-JUN-73"$"05-JUN-73"$""$"...
1  3$"000000003"$"0"$"05-JUN-73"$"05-JUN-73"$""$"...
2  4$"000000004"$"0"$"05-JUN-73"$"05-JUN-73"$""$"...

--- Preview of: seriousness_lx.txt ---

           2001$"01"$"Serious"$"Grave"
0  2002$"02"$"Not Serious"$"Non grave"

--- Preview of: source_lx.txt ---

           1001$"01"$"Community"$"CommunautÃ©"
0  1002$"02"$"Clinical Study"$"Essai Clinique"
1              1003$"03"$"Hospital"$"HÃ´pital"
2       1004$"04"$"Distributor"$"Distributeur"

In [16]:
!gcloud storage ls gs://my-pharma-data-project/**

gs://my-pharma-data-project/adverse_events.csv
gs://my-pharma-data-project/adverse_events_summary.csv
gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/drug_product_ingredients.txt
gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/drug_products.txt
gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/gender_lx.txt
gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/literature_reference.txt
gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/outcome_lx.txt
gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/reactions.txt
gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/report_drug.txt
gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/report_drug_indication.txt
gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/report_links.txt
gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/report_type_lx.txt
gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/reports.txt
gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/seriousness_lx.txt
gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/source_lx.txt
gs://my-pharma-data-project/clinical_trials.csv
gs://my-pharma-data-project/data_dictionary.csv
gs://my-pharma-data-project/drugs_overview.csv
gs://my-pharma-data-project/search_trends.csv
gs://my-pharma-data-project/stock_prices.csv
gs://my-pharma-data-project/wikipedia_summaries.csv

In [17]:
import pandas as pd

# The complete list of files you provided
all_files = [
    'gs://my-pharma-data-project/adverse_events.csv',
    'gs://my-pharma-data-project/adverse_events_summary.csv',
    'gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/drug_product_ingredients.txt',
    'gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/drug_products.txt',
    'gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/gender_lx.txt',
    'gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/literature_reference.txt',
    'gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/outcome_lx.txt',
    'gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/reactions.txt',
    'gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/report_drug.txt',
    'gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/report_drug_indication.txt',
    'gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/report_links.txt',
    'gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/report_type_lx.txt',
    'gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/reports.txt',
    'gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/seriousness_lx.txt',
    'gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/source_lx.txt',
    'gs://my-pharma-data-project/clinical_trials.csv',
    'gs://my-pharma-data-project/data_dictionary.csv',
    'gs://my-pharma-data-project/drugs_overview.csv',
    'gs://my-pharma-data-project/search_trends.csv',
    'gs://my-pharma-data-project/stock_prices.csv',
    'gs://my-pharma-data-project/wikipedia_summaries.csv'
]

for path in all_files:
    filename = path.split('/')[-1]
    print(f"\n{'='*20}\nPREVIEW: {filename}\n{'='*20}")
    try:
        # Detect format: CSV uses commas, TXT uses tabs
        sep = ',' if path.endswith('.csv') else '\t'
        df = pd.read_csv(path, sep=sep, encoding='latin1')

        display(df.head(3))
        print(f"Columns: {list(df.columns)}")
    except Exception as e:
        print(f"Error loading {filename}: {e}")

====================
PREVIEW: adverse_events.csv
====================

,safetyreportid,generic_name,brand_queried,receive_date,country,serious,seriousness_death,seriousness_lifethreatening,seriousness_hospitalization,seriousness_disabling,patient_age,patient_age_unit,patient_sex,patient_weight_kg,reaction,reaction_outcome
0,10188271,semaglutide,OZEMPIC,2014-05-22,US,True,False,False,True,True,81.0,Year,Female,NaN,Stenosis,Unknown
1,10188271,semaglutide,OZEMPIC,2014-05-22,US,True,False,False,True,True,81.0,Year,Female,NaN,Hunger,Unknown
2,10188271,semaglutide,OZEMPIC,2014-05-22,US,True,False,False,True,True,81.0,Year,Female,NaN,Visual impairment,Unknown

Columns: ['safetyreportid', 'generic_name', 'brand_queried', 'receive_date', 'country', 'serious', 'seriousness_death', 'seriousness_lifethreatening', 'seriousness_hospitalization', 'seriousness_disabling', 'patient_age', 'patient_age_unit', 'patient_sex', 'patient_weight_kg', 'reaction', 'reaction_outcome']

====================
PREVIEW: adverse_events_summary.csv
====================

,generic_name,reaction,report_count,pct_serious,pct_hospitalization,pct_death,median_age,pct_female
0,albiglutide,Device use error,2699,0.0189,0.0052,0.0,58.0,0.5873
1,albiglutide,Accidental exposure to product,840,0.0202,0.0060,0.0,58.0,0.5274
2,albiglutide,Drug dose omission,662,0.0468,0.0211,0.0,59.0,0.6073

Columns: ['generic_name', 'reaction', 'report_count', 'pct_serious', 'pct_hospitalization', 'pct_death', 'median_age', 'pct_female']

====================
PREVIEW: drug_product_ingredients.txt
====================

  113507991$"1135"$"PROCHLORPERAZINE MESYLATE INJ 5MG/ML"$"7991"$"prochlorperazine"
0  3806807996$"38068"$"STELAZINE"$"7996"$"trifluo...
1  3806907996$"38069"$"STELABID"$"7996"$"trifluop...
2  4346007996$"43460"$"TRIFLURIN"$"7996"$"trifluo...

Columns: ['113507991$"1135"$"PROCHLORPERAZINE MESYLATE INJ 5MG/ML"$"7991"$"prochlorperazine"']

====================
PREVIEW: drug_products.txt
====================

                                   1$"DELATESTRYL"
0                     2$"DELATESTRYL INJ 200MG/ML"
1  3$"TEMPRA CEMENT POWDER AND TEMPRA POLY LIQUID"
2                                     4$"MAGNOLAX"

Columns: ['1$"DELATESTRYL"']

====================
PREVIEW: gender_lx.txt
====================

     41$"1"$"Male"$"Masculin"
0  42$"2"$"Female"$"FÃ©minin"

Columns: ['41$"1"$"Male"$"Masculin"']

====================
PREVIEW: literature_reference.txt
====================
Error loading literature_reference.txt: Error tokenizing data. C error: Expected 1 fields in line 255717, saw 2


====================
PREVIEW: outcome_lx.txt
====================

                      1906$"06"$"Unknown"$"Inconnue"
0         1907$"07"$"Recovered/resolved"$"GuÃ©rison"
1  1908$"08"$"Recovering/resolving"$"GuÃ©rison en...
2  1909$"09"$"Not recovered/not resolved"$"Non rÃ...

Columns: ['1906$"06"$"Unknown"$"Inconnue"']

====================
PREVIEW: reactions.txt
====================

  5601$"56"$""$""$""$"Rash"$"Rash"$"Skin and subcutaneous tissue disorders"$"Affections de la peau et du tissu sous-cutanÃ©"$"v.27.1"
0  5701$"57"$""$""$""$"Irritability"$"Irritabilit...
1  5801$"58"$""$""$""$"Conjunctivitis"$"Conjoncti...
2  5803$"58"$""$""$""$"Photophobia"$"Photophobie"...

Columns: ['5601$"56"$""$""$""$"Rash"$"Rash"$"Skin and subcutaneous tissue disorders"$"Affections de la peau et du tissu sous-cutanÃ©"$"v.27.1"']

====================
PREVIEW: report_drug.txt
====================

  177$"183405"$"44130"$"PRIMROSE OIL"$"Concomitant"$"Concomitant"$"Unknown"$"Inconnu"$""$""$""$""$""$""$""$""$""$""$""$""$"NOT SPECIFIED"$"NON PRÃCISÃE"
0  178$"183405"$"21895"$"IRON"$"Concomitant"$"Con...
1  179$"183405"$"39717"$"NIZATIDINE"$"Concomitant...
2  180$"183405"$"36464"$"PROPRANOLOL"$"Concomitan...

Columns: ['177$"183405"$"44130"$"PRIMROSE OIL"$"Concomitant"$"Concomitant"$"Unknown"$"Inconnu"$""$""$""$""$""$""$""$""$""$""$""$""$"NOT SPECIFIED"$"NON PRÃ\x89CISÃ\x89E"']

====================
PREVIEW: report_drug_indication.txt
====================

  3891781$"300248"$"8248"$"REMICADE"$"Crohn's disease"$"Maladie de Crohn"
0  4016384$"300172"$"6353"$"APO-PAROXETINE"$"Depr...
1  3977480$"300451"$"4743"$"BETASERON"$"Secondary...
2  3891805$"300273"$"9473"$"CHAMPIX"$"Smoking ces...

Columns: ['3891781$"300248"$"8248"$"REMICADE"$"Crohn\'s disease"$"Maladie de Crohn"']

====================
PREVIEW: report_links.txt
====================

  1432411$"143241"$"Duplicate"$"Doublon"$"000307652"
0  1433901$"143390"$"Duplicate"$"Doublon"$"000143...
1  1436082$"143608"$"Duplicate"$"Doublon"$"000323...
2  1436211$"143621"$"Duplicate"$"Doublon"$"000338...

Columns: ['1432411$"143241"$"Duplicate"$"Doublon"$"000307652"']

====================
PREVIEW: report_type_lx.txt
====================

                 70095001$"5001"$"CMDSNet"$"ResSCMM"
0  70095002$"5002"$"Investigational Testing"$"Ess...
1                70095007$"5"$"Published"$"PubliÃ©e"
2  70095009$"7"$"Spontaneous"$"DÃ©claration spont...

Columns: ['70095001$"5001"$"CMDSNet"$"ResSCMM"']

====================
PREVIEW: reports.txt
====================

  1$"000000001"$"0"$"05-JUN-73"$"05-JUN-73"$""$"7"$"Spontaneous"$"DÃ©claration spontanÃ©e"$"2"$"Female"$"FÃ©minin"$"62"$"62"$"Years"$"AnnÃ©es"$"06"$"Unknown"$"Inconnue"$"66"$"Kilogram"$"Kilogramme"$"155"$"Centimeter"$"CentimÃ¨tres"$"02"$"Not Serious"$"Non grave"$""$""$""$""$""$""$"Physician"$"Physicien"$""$""$""$""$""$""
0  2$"000000002"$"0"$"05-JUN-73"$"05-JUN-73"$""$"...
1  3$"000000003"$"0"$"05-JUN-73"$"05-JUN-73"$""$"...
2  4$"000000004"$"0"$"05-JUN-73"$"05-JUN-73"$""$"...

Columns: ['1$"000000001"$"0"$"05-JUN-73"$"05-JUN-73"$""$"7"$"Spontaneous"$"DÃ©claration spontanÃ©e"$"2"$"Female"$"FÃ©minin"$"62"$"62"$"Years"$"AnnÃ©es"$"06"$"Unknown"$"Inconnue"$"66"$"Kilogram"$"Kilogramme"$"155"$"Centimeter"$"CentimÃ¨tres"$"02"$"Not Serious"$"Non grave"$""$""$""$""$""$""$"Physician"$"Physicien"$""$""$""$""$""$""']

====================
PREVIEW: seriousness_lx.txt
====================

           2001$"01"$"Serious"$"Grave"
0  2002$"02"$"Not Serious"$"Non grave"

Columns: ['2001$"01"$"Serious"$"Grave"']

====================
PREVIEW: source_lx.txt
====================

           1001$"01"$"Community"$"CommunautÃ©"
0  1002$"02"$"Clinical Study"$"Essai Clinique"
1              1003$"03"$"Hospital"$"HÃ´pital"
2       1004$"04"$"Distributor"$"Distributeur"

Columns: ['1001$"01"$"Community"$"CommunautÃ©"']

====================
PREVIEW: clinical_trials.csv
====================

,drug_query,nct_id,brief_title,overall_status,start_date,completion_date,phase,study_type,enrollment,conditions,lead_sponsor
0,semaglutide,NCT05144984,A Research Study Looking at How Well a Combina...,COMPLETED,2021-11-29,2023-03-23,PHASE2,INTERVENTIONAL,500,"Diabetes Mellitus, Type 2",Novo Nordisk A/S
1,semaglutide,NCT04538352,Transition From Basal/Bolus to Once-weekly Sub...,COMPLETED,2021-01-18,2023-11-01,PHASE4,INTERVENTIONAL,60,Type 2 Diabetes,The Cleveland Clinic
2,semaglutide,NCT05521256,A Research Study of a New Medicine NNC0113-685...,COMPLETED,2022-08-26,2023-03-27,PHASE1,INTERVENTIONAL,70,Healthy Volunteers; Type 2 Diabetes,Novo Nordisk A/S

Columns: ['drug_query', 'nct_id', 'brief_title', 'overall_status', 'start_date', 'completion_date', 'phase', 'study_type', 'enrollment', 'conditions', 'lead_sponsor']

====================
PREVIEW: data_dictionary.csv
====================

                 file        column    type                  description
0  drugs_overview.csv  generic_name  string      Generic (INN) drug name
1  drugs_overview.csv   brand_names  string  Brand names, '; ' separated
2  drugs_overview.csv  manufacturer  string         Primary manufacturer

Columns: ['file', 'column', 'type', 'description']

====================
PREVIEW: drugs_overview.csv
====================

,generic_name,brand_names,manufacturer,indication,fda_first_approval_date,is_investigational,drug_class
0,semaglutide,OZEMPIC; WEGOVY; RYBELSUS,Novo Nordisk,type-2-diabetes/obesity,2017-12-05,False,GLP-1 receptor agonist
1,tirzepatide,MOUNJARO; ZEPBOUND,Eli Lilly,type-2-diabetes/obesity,2022-05-13,False,dual GIP/GLP-1 receptor agonist
2,liraglutide,VICTOZA; SAXENDA,Novo Nordisk,type-2-diabetes/obesity,2010-01-25,False,GLP-1 receptor agonist

Columns: ['generic_name', 'brand_names', 'manufacturer', 'indication', 'fda_first_approval_date', 'is_investigational', 'drug_class']

====================
PREVIEW: search_trends.csv
====================

         date geo   term  search_interest
0  2018-01-01  AE  GLP-1                0
1  2018-02-01  AE  GLP-1                0
2  2018-03-01  AE  GLP-1                0

Columns: ['date', 'geo', 'term', 'search_interest']

====================
PREVIEW: stock_prices.csv
====================

,date,ticker,company,open,high,low,close,adj_close,volume
0,2017-01-03,LLY,Eli Lilly & Company,73.940002,74.669998,73.540001,74.599998,64.412567,3622700
1,2017-01-04,LLY,Eli Lilly & Company,74.949997,75.000000,74.379997,74.720001,64.516159,3021600
2,2017-01-05,LLY,Eli Lilly & Company,74.930000,77.870003,74.430000,75.589996,65.267349,3310800

Columns: ['date', 'ticker', 'company', 'open', 'high', 'low', 'close', 'adj_close', 'volume']

====================
PREVIEW: wikipedia_summaries.csv
====================

,generic_name,wiki_title,summary,image_url
0,semaglutide,Semaglutide,Semaglutide is an anti-diabetic medication use...,https://upload.wikimedia.org/wikipedia/commons...
1,tirzepatide,Tirzepatide,Tirzepatide is a gastric inhibitory polypeptid...,https://upload.wikimedia.org/wikipedia/commons...
2,liraglutide,Liraglutide,"Liraglutide, sold under the brand name Victoza...",https://upload.wikimedia.org/wikipedia/commons...

Columns: ['generic_name', 'wiki_title', 'summary', 'image_url']

In [18]:
import pandas as pd

def load_canada_data(path):
    # These files appear to use '$' as a separator and have quotes around values
    return pd.read_csv(path, sep=r'\$', engine='python', encoding='latin1')

# Test it on reports.txt
df_reports = load_canada_data('gs://my-pharma-data-project/canada-adverse-data/cvponline_extract_20241130/reports.txt')
print("Fixed Reports Columns:", df_reports.columns.tolist())
display(df_reports.head(3))

Fixed Reports Columns: ['"1"', '"000000001"', '"0"', '"05-JUN-73"', '"05-JUN-73".1', '""', '"7"', '"Spontaneous"', '"DÃ©claration spontanÃ©e"', '"2"', '"Female"', '"FÃ©minin"', '"62"', '"62".1', '"Years"', '"AnnÃ©es"', '"06"', '"Unknown"', '"Inconnue"', '"66"', '"Kilogram"', '"Kilogramme"', '"155"', '"Centimeter"', '"CentimÃ¨tres"', '"02"', '"Not Serious"', '"Non grave"', '"".1', '"".2', '"".3', '"".4', '"".5', '"".6', '"Physician"', '"Physicien"', '"".7', '"".8', '"".9', '"".10', '"".11', '"".12']

,"""1""","""000000001""","""0""","""05-JUN-73""","""05-JUN-73"".1","""""","""7""","""Spontaneous""","""DÃ©claration spontanÃ©e""","""2""",...,""""".5",""""".6","""Physician""","""Physicien""",""""".7",""""".8",""""".9",""""".10",""""".11",""""".12"
0,"""2""","""000000002""","""0""","""05-JUN-73""","""05-JUN-73""","""""","""7""","""Spontaneous""","""DÃ©claration spontanÃ©e""","""2""",...,"""""","""""","""""","""""","""03""","""Hospital""","""HÃ´pital""","""""","""""",""""""
1,"""3""","""000000003""","""0""","""05-JUN-73""","""05-JUN-73""","""""","""7""","""Spontaneous""","""DÃ©claration spontanÃ©e""","""1""",...,"""""","""""","""""","""""","""03""","""Hospital""","""HÃ´pital""","""""","""""",""""""
2,"""4""","""000000004""","""0""","""05-JUN-73""","""05-JUN-73""","""""","""7""","""Spontaneous""","""DÃ©claration spontanÃ©e""","""2""",...,"""""","""""","""""","""""","""03""","""Hospital""","""HÃ´pital""","""""","""""",""""""